version: '3.8'

services:
  cloud-server:
    build: .
    container_name: cloud_server
    command: python cloud_server.py
    ports:
      - "9000:9000"
    networks:
      - monitoring-net

  core-aggregator-1:
    build: .
    container_name: core_aggregator_1
    command: python core_aggregator.py --node-id 1 --listen-port 8001 --peers "core-aggregator-2:8002,core-aggregator-3:8003"
    ports:
      - "8001:8001"
    depends_on:
      - cloud-server
    networks:
      - monitoring-net

  core-aggregator-2:
    build: .
    container_name: core_aggregator_2
    command: python core_aggregator.py --node-id 2 --listen-port 8002 --peers "core-aggregator-1:8001,core-aggregator-3:8003"
    ports:
      - "8002:8002"
    depends_on:
      - cloud-server
    networks:
      - monitoring-net

  core-aggregator-3:
    build: .
    container_name: core_aggregator_3
    command: python core_aggregator.py --node-id 3 --listen-port 8003 --peers "core-aggregator-1:8001,core-aggregator-2:8002"
    ports:
      - "8003:8003"
    depends_on:
      - cloud-server
    networks:
      - monitoring-net

  edge-node-1:
    build: .
    container_name: edge_node_1
    command: python edge_agent.py --edge-id Edge_01 --core-host core-aggregator-1 --core-port 8001
    depends_on:
      - core-aggregator-1
    networks:
      - monitoring-net

  edge-node-2:
    build: .
    container_name: edge_node_2
    command: python edge_agent.py --edge-id Edge_02 --core-host core-aggregator-2 --core-port 8002
    depends_on:
      - core-aggregator-2
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge